pub(crate) mod actions;
mod agent_launcher_menu;
mod agentbox;
pub(crate) mod appearance;
pub(crate) mod automations_row;
mod bots;
mod collections;
mod decorations;
mod disclosure;
pub(crate) mod drag;
mod drag_source;
mod empty;
mod host;
pub(crate) mod hover_actions;
pub(crate) mod icons;
pub(crate) mod images;
mod machines;
mod menu_state;
pub(crate) mod menus;
pub(crate) mod model;
pub(crate) mod navigation;
#[cfg(target_os = "macos")]
mod pointer;
mod project_header;
pub(crate) mod project_hover;
mod project_status;
mod rename;
pub(crate) mod render;
pub(crate) mod row_drag;
pub(crate) mod rows;
mod scroll;
mod scroll_fade;
mod section_move;
mod sections;
pub(crate) mod selectors;
mod session_hover;
mod session_list;
pub(crate) mod sessions;
mod space_drag;
mod space_gesture;
pub(crate) mod state;
mod status;
mod sticky;
mod threads;
mod tooltips;
pub(crate) mod usage;
mod work_chips;
mod workspace_tile;
