//! The harness-injected turn classifier.
//!
//! Ported from `packages/core-ui/chat/session-chat-noise.ts`, tag and prefix constants verbatim.
//!
//! Design law (do not "improve" this): match only tags OBSERVED from harnesses, never a broad kebab
//! shape. A real prompt starting with a custom `<my-element>` or a Grok `<user_query>` envelope is a
//! genuine user turn; misclassifying it hides the turn. `<channel>` is only matched in its
//! attributed `<channel source=` form, because a bare `<channel>` is a real RSS or XML paste.
//!
//! Second law: a matched turn is SUPPRESSED, not deleted. Everything the terminal itself prints
//! renders as a one-line collapsed marker that expands to the full text; deleting them is exactly
//! what reads as "chat is missing messages". Only the records the terminal never shows either
//! (system reminders, hook plumbing) stay hidden.

use ghostex_gx_protocol::{ChatBlock, ChatMessage, ChatRole, ChatSource};
use serde_json::{json, Map, Value};

use crate::transcript::agent_message::parse_cross_session_message;
use crate::transcript::foreign::{decode_escaped_markup, effort_label, parse_command_envelope};
use crate::transcript::jsstr::{
    ascii_lower, collapse_whitespace, js_trim, js_trim_start, split_newlines,
};
use crate::transcript::prose::joined_text;

/// Claude: the row derived from `/compact`'s local-command output.
const COMPACTION_COMPLETED_LABEL: &str = "Compaction completed";
/// Hermes: a `/compress` that found nothing to compact.
const NOTHING_TO_COMPRESS_LABEL: &str = "Nothing to compress";
/*
Codex: the row gxserver decodes from the rollout's `ContextCompaction` thread item
(`CONTEXT_COMPACTED_STATUS_TEXT` in server/src/session_chat.rs; keep the two spellings in step).
Codex has no compaction completion output to parse, so that transcript item is the ONLY durable
evidence a compaction happened. Matched exactly, and only on a transcript-decoded system turn, so a
user typing the same words still reads as their own message.
*/
const CONTEXT_COMPACTED_LABEL: &str = "Context compacted";

/// A short harness turn reads better as one muted line of prose than as a chevron the reader has to
/// click to learn it said "exit code 0". Long output still collapses.
const INLINE_BODY_MAX_CHARS: usize = 320;
const INLINE_BODY_MAX_LINES: usize = 4;

/// Harness tags that render as a collapsed, expandable marker.
fn collapsed_tag_label(tag: &str) -> Option<&'static str> {
    Some(match tag {
        "agent-message" => "Message from another session",
        "bash-input" => "Local command",
        "bash-stderr" | "bash-stdout" => "Local command output",
        "command-args" | "command-message" | "command-name" => "Slash command",
        "cross-session-message" => "Message from another session",
        "local-command-caveat" | "local-command-stderr" | "local-command-stdout" => {
            "Local command output"
        }
        "task-notification" => "Task notification",
        "teammate-message" => "Message from another session",
        "user-memory-input" => "Memory note",
        _ => return None,
    })
}

/// Harness tags the agent's own TUI never prints either: they stay hidden.
fn is_hidden_tag(tag: &str) -> bool {
    matches!(
        tag,
        "fork-boilerplate"
            | "mcp-polling-update"
            | "mcp-resource-update"
            | "system-reminder"
            | "user-prompt-submit-hook"
    )
}

const COLLAPSED_PREFIX_LABELS: [(&str, &str); 7] = [
    ("<channel source=", "Message from another session"),
    ("[request interrupted", "Interrupted"),
    ("a message arrived from ", "Message from another session"),
    (
        "another claude session sent a message",
        "Message from another session",
    ),
    ("no response requested.", "Message from another session"),
    (
        "caveat: the messages below were generated by the user while running local commands",
        "Local command output",
    ),
    (
        "this session is being continued from a previous conversation",
        "Session continued from a previous conversation",
    ),
];

/// `^<([a-z][a-z0-9-]*)(?:[\s>]|$)` against the lowercased, trimmed text.
fn leading_tag_name(normalized: &str) -> Option<&str> {
    let rest = normalized.strip_prefix('<')?;
    if !rest.as_bytes().first().is_some_and(u8::is_ascii_lowercase) {
        return None;
    }
    let end = rest
        .bytes()
        .take_while(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || *byte == b'-')
        .count();
    let after = rest[end..].chars().next();
    match after {
        None => Some(&rest[..end]),
        Some(character) if character == '>' || crate::transcript::jsstr::is_js_space(character) => {
            Some(&rest[..end])
        }
        _ => None,
    }
}

/// `</?[a-z][a-z0-9-]*(?:\s[^>]*)?>` case-insensitively, removed everywhere.
fn strip_markup_tags(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut out = String::with_capacity(text.len());
    let mut cursor = 0;
    while let Some(found) = text[cursor..].find('<') {
        let open = cursor + found;
        let mut at = open + 1;
        if bytes.get(at) == Some(&b'/') {
            at += 1;
        }
        let name_len = text[at..]
            .bytes()
            .take_while(|byte| byte.is_ascii_alphanumeric() || *byte == b'-')
            .count();
        let valid_name = name_len > 0 && bytes[at].is_ascii_alphabetic();
        let mut end = None;
        if valid_name {
            let rest = &text[at + name_len..];
            if rest.starts_with('>') {
                end = Some(at + name_len + 1);
            } else if rest.starts_with(char::is_whitespace) {
                if let Some(close) = rest.find('>') {
                    if !rest[..close].contains('>') {
                        end = Some(at + name_len + close + 1);
                    }
                }
            }
        }
        match end {
            Some(end) => {
                out.push_str(&text[cursor..open]);
                cursor = end;
            }
            None => {
                out.push_str(&text[cursor..open + 1]);
                cursor = open + 1;
            }
        }
    }
    out.push_str(&text[cursor..]);
    out
}

/// `^<(?:bash-(?:input|stdout)|command-name|local-command-stdout) data-ghostex-escaped="html">`.
fn is_escaped_harness_marker(text: &str) -> bool {
    let lower = ascii_lower(js_trim_start(text));
    [
        "bash-input",
        "bash-stdout",
        "command-name",
        "local-command-stdout",
    ]
    .iter()
    .any(|tag| lower.starts_with(&format!("<{tag} data-ghostex-escaped=\"html\">")))
}

/// Text left once the harness markup is removed; empty means there is nothing to expand.
pub fn suppressed_turn_body(text: &str) -> String {
    let body = js_trim(&strip_markup_tags(text)).to_string();
    if !is_escaped_harness_marker(text) {
        return body;
    }
    decode_escaped_markup(&body)
}

/*
 * /compact's local-command stdout is just a dim "Compacted" wrapped in ANSI style codes; readers
 * deserve "Compaction completed" instead of a generic "Local command output" marker. Deliberately
 * lenient: strip SGR sequences (with or without the ESC byte surviving transcript encoding), fold
 * whitespace, and accept the wording variants harnesses have used.
 */
fn strip_ansi(text: &str) -> String {
    let bytes = text.as_bytes();
    let mut out = String::with_capacity(text.len());
    let mut cursor = 0;
    while cursor < text.len() {
        let rest = &text[cursor..];
        let lead = if rest.starts_with('\u{1b}') {
            1
        } else if rest.starts_with('\u{9b}') {
            2
        } else {
            0
        };
        let bracket = cursor + lead;
        if bytes.get(bracket) == Some(&b'[') {
            let digits = text[bracket + 1..]
                .bytes()
                .take_while(|byte| byte.is_ascii_digit() || *byte == b';')
                .count();
            if (1..=8).contains(&digits) && bytes.get(bracket + 1 + digits) == Some(&b'm') {
                cursor = bracket + digits + 2;
                continue;
            }
        }
        let step = rest.chars().next().map_or(1, char::len_utf8);
        out.push_str(&rest[..step]);
        cursor += step;
    }
    out
}

/// Terminal styling is not content: a transcript row carries the agent's SGR codes verbatim, and a
/// chat view has no terminal to interpret them, so they must never reach the DOM.
pub fn strip_chat_ansi(text: &str) -> String {
    strip_ansi(text)
}

fn normalized_suppressed_turn_body(text: &str) -> String {
    js_trim(&collapse_whitespace(&strip_ansi(&suppressed_turn_body(
        text,
    ))))
    .to_string()
}

/// `^compact(?:ed|ing|ion)\b(?:\s+(?:is\s+)?(?:complete[d]?|done|finished|successful(?:ly)?))?(?:\s*\([^)]*\))?\s*[.!…]*$`
/// case-insensitively.
fn leading_space_len(value: &str) -> usize {
    value
        .chars()
        .take_while(|character| crate::transcript::jsstr::is_js_space(*character))
        .map(char::len_utf8)
        .sum()
}

fn is_compaction_output(line: &str) -> bool {
    let lower = ascii_lower(line);
    let Some(stem) = ["compacted", "compacting", "compaction"]
        .into_iter()
        .find(|stem| lower.starts_with(stem))
    else {
        return false;
    };
    let mut rest = &lower[stem.len()..];
    // `\b` after the stem: the next character must not be a word character.
    if rest
        .as_bytes()
        .first()
        .is_some_and(|byte| byte.is_ascii_alphanumeric() || *byte == b'_')
    {
        return false;
    }
    let space = leading_space_len(rest);
    if space > 0 {
        let after = &rest[space..];
        let after_is = after.strip_prefix("is").and_then(|value| {
            let inner = leading_space_len(value);
            (inner > 0).then(|| &value[inner..])
        });
        // The longer spelling first, because `complete[d]?` and `successful(?:ly)?` are greedy.
        for candidate in [after_is, Some(after)].into_iter().flatten() {
            if let Some(word) = [
                "completed",
                "complete",
                "done",
                "finished",
                "successfully",
                "successful",
            ]
            .into_iter()
            .find(|word| candidate.starts_with(word))
            {
                rest = &candidate[word.len()..];
                break;
            }
        }
    }
    let space = leading_space_len(rest);
    if rest[space..].starts_with('(') {
        if let Some(close) = rest[space + 1..].find(')') {
            rest = &rest[space + 1 + close + 1..];
        }
    }
    js_trim(rest)
        .chars()
        .all(|character| matches!(character, '.' | '!' | '\u{2026}'))
}

/// CDXC:SessionChat 2026-09-11 WHY:
/// Claude appends one receipt line per PostCompact hook. Ghostex's hook answers `{"continue":true}`,
/// but a hook another tool registered answers `{}` (or any object), and matching the JSON demoted the
/// whole row to a raw "Local command output" marker whenever a second hook was installed. Only "ran
/// and succeeded" matters here; a failed receipt still falls through and stays readable.
fn is_post_compact_success(line: &str) -> bool {
    let lower = ascii_lower(line);
    let Some(rest) = lower.strip_prefix("postcompact") else {
        return false;
    };
    let space = leading_space_len(rest);
    if space == 0 {
        return false;
    }
    let Some(rest) = rest[space..].strip_prefix('[') else {
        return false;
    };
    // `.*` is greedy, so the last bracket closes the list.
    let Some(close) = rest.rfind(']') else {
        return false;
    };
    let tail = &rest[close + 1..];
    let space = leading_space_len(tail);
    space > 0 && tail[space..].starts_with("completed successfully:")
}

/*
CDXC:SessionChat 2026-09-28 WHY:
Carries the Hermes compress DECISION on `hermes_compacting_activity`
(server/src/session_chat_terminal_activity/line_parsers.rs) into the transcript. The card shows the run and the
transcript's "Context compacted" row is the one line, so a `/compress` output stays hidden while it
runs and once it compacted, and one that found nothing to compact becomes the "Nothing to compress"
pill. Any other ending (skipped for the lock, refused, aborted, fallback, failed) keeps its output:
that is news the reader has to see.
*/
fn hermes_compress_result(text: &str) -> Option<SuppressedTurn> {
    let body = strip_ansi(&suppressed_turn_body(text));
    let lines: Vec<&str> = split_newlines(&body)
        .into_iter()
        .map(|line| js_trim(line).trim_start_matches(|ch: char| !ch.is_alphanumeric() && ch != '('))
        .filter(|line| !line.is_empty())
        .collect();
    if lines.iter().any(|line| {
        line.starts_with("No changes from compression: ")
            || line.starts_with("Nothing to compress yet.")
            || line.starts_with("(._.) Not enough conversation to compress")
    }) {
        return Some(SuppressedTurn::Status {
            label: NOTHING_TO_COMPRESS_LABEL.to_string(),
            tone: None,
        });
    }
    if !lines
        .first()
        .is_some_and(|line| line.starts_with("Compressing context"))
    {
        return None;
    }
    match lines
        .iter()
        .find(|line| line.starts_with("Compressed") || line.starts_with("Compression"))
    {
        None => Some(SuppressedTurn::Hidden),
        Some(ending) if ending.starts_with("Compressed: ") => Some(SuppressedTurn::Hidden),
        Some(_) => None,
    }
}

fn is_compaction_command_output(text: &str) -> bool {
    let body = strip_ansi(&suppressed_turn_body(text));
    let lines: Vec<&str> = split_newlines(&body)
        .into_iter()
        .map(js_trim)
        .filter(|line| !line.is_empty())
        .collect();
    let Some((completion, hook_results)) = lines.split_first() else {
        return false;
    };
    is_compaction_output(completion)
        && hook_results
            .iter()
            .all(|line| is_post_compact_success(line))
}

/// What `/model`'s local-command output said.
struct ModelDefaultOutput {
    model: String,
    /// Trailing sentence the harness added, for example a settings.json pin warning.
    note: Option<String>,
    /// Display label of the effort a session-only pick set in the same sentence.
    effort: Option<String>,
    /// Where "and saved as your default…" or "for this session only" ends in the normalized body.
    scope_end: usize,
}

/*
 * Claude Code appends a second line when a `.claude/settings.json` model pin disagrees with the
 * picked model, so this cannot be end-anchored: the trailing sentence is captured as a note and
 * reported as its own status row instead of demoting the whole turn to a raw marker.
 */
fn model_set_by_command_output(text: &str) -> Option<ModelDefaultOutput> {
    const HEAD: &str = "set model to";
    let body = normalized_suppressed_turn_body(text);
    // `to_ascii_lowercase` is byte-for-byte, so an offset into one string is the same offset in the
    // other and the matched spans can be read back out of the original casing.
    let lower = ascii_lower(&body);
    let after_head = lower.strip_prefix(HEAD)?;
    let space = leading_space_len(after_head);
    if space == 0 {
        return None;
    }
    let tail = &body[HEAD.len() + space..];
    let tail_lower = &lower[HEAD.len() + space..];
    // `(.+?)\s+(?:and saved as your default for new sessions|for this session only)`, lazy: the
    // earliest of the two phrases wins.
    let (at, length) = [
        "and saved as your default for new sessions",
        "for this session only",
    ]
    .into_iter()
    .filter_map(|phrase| tail_lower.find(phrase).map(|at| (at, phrase.len())))
    .min_by_key(|(at, _)| *at)?;
    let model = js_trim_end(&tail[..at]);
    // `(.+?)` needs a character and the `\s+` before the phrase needs a space.
    if model.is_empty() || model.len() == at {
        return None;
    }
    let model = model.to_string();
    let scope_end = HEAD.len() + space + at + length;
    let mut rest = &tail[at + length..];

    // `(?:\s+with\s+`?([^\s`]+)`?\s+effort)?`
    let mut effort = None;
    let space = leading_space_len(rest);
    if space > 0 && ascii_lower(&rest[space..]).starts_with("with") {
        {
            let after_with = &rest[space + "with".len()..];
            let inner = leading_space_len(after_with);
            if inner > 0 {
                let value = &after_with[inner..];
                let value = value.strip_prefix('`').unwrap_or(value);
                let token_len: usize = value
                    .chars()
                    .take_while(|character| {
                        !crate::transcript::jsstr::is_js_space(*character) && *character != '`'
                    })
                    .map(char::len_utf8)
                    .sum();
                let after_token = &value[token_len..];
                let after_token = after_token.strip_prefix('`').unwrap_or(after_token);
                let gap = leading_space_len(after_token);
                if token_len > 0
                    && gap > 0
                    && ascii_lower(&after_token[gap..]).starts_with("effort")
                {
                    effort = Some(value[..token_len].to_string());
                    rest = &after_token[gap + "effort".len()..];
                }
            }
        }
    }

    // `\s*(?:[.!…]+(?=\s|$))?\s*(.*)$`
    let rest = js_trim_start(rest);
    let punctuation: usize = rest
        .chars()
        .take_while(|character| matches!(character, '.' | '!' | '\u{2026}'))
        .map(char::len_utf8)
        .sum();
    let after_punctuation = if punctuation > 0
        && rest[punctuation..]
            .chars()
            .next()
            .is_none_or(crate::transcript::jsstr::is_js_space)
    {
        &rest[punctuation..]
    } else {
        rest
    };
    let note = js_trim(after_punctuation).to_string();
    Some(ModelDefaultOutput {
        model,
        note: if note.is_empty() { None } else { Some(note) },
        // A session-only pick that moved the effort rail reports it in the same sentence.
        effort: effort.map(|value| effort_label(&value)),
        scope_end,
    })
}

/// CDXC:SessionChat 2026-10-01 DECISION:
/// User: "i dont like seeing these 2 like this, please combine the 2 where it makes sense" about a "Set model to Sonnet 5.5" pill followed by a "Set effort level to Low" pill. A model pick saved as the default runs `/model` then `/effort`, and Claude records each output as its own turn; an `/effort` output that comes straight after a `/model` output that named no effort folds into it, so the pair reads as the one sentence a session-only pick prints ("Set model to Sonnet 5.5 with Low effort"). Supersedes the 2026-09-09 decision's separate effort pill beside the model change; `/effort` on its own keeps its own pill.
pub fn fold_model_effort_pairs(messages: &[ChatMessage]) -> Vec<ChatMessage> {
    let output_text = |message: &ChatMessage| {
        let text = js_trim(&joined_text(&message.blocks)).to_string();
        (harness_injected_turn_label(&text).as_deref() == Some("Local command output"))
            .then_some(text)
    };
    let mut folded: Vec<ChatMessage> = Vec::with_capacity(messages.len());
    for message in messages {
        let effort = output_text(message)
            .as_deref()
            .and_then(effort_set_by_command_output);
        let previous = folded.last().and_then(|previous| {
            let text = output_text(previous)?;
            let model = model_set_by_command_output(&text)?;
            (previous.role == message.role && model.effort.is_none()).then_some((text, model))
        });
        let (Some(effort), Some((text, model))) = (effort, previous) else {
            folded.push(message.clone());
            continue;
        };
        let body = normalized_suppressed_turn_body(&text);
        let (said, rest) = body.split_at(model.scope_end);
        let sentence = format!("{said} with `{effort}` effort{rest}");
        if let Some(previous) = folded.last_mut() {
            previous.blocks = vec![ChatBlock::Text {
                text: crate::session::app_commands::escaped_marker(
                    "local-command-stdout",
                    &sentence,
                ),
            }];
        }
    }
    folded
}

/// `^set effort level to\s+`?([^\s`]+)`?` case-insensitively.
fn effort_set_by_command_output(text: &str) -> Option<String> {
    const HEAD: &str = "set effort level to";
    let body = normalized_suppressed_turn_body(text);
    let after_head = ascii_lower(&body).strip_prefix(HEAD)?.to_string();
    let space = leading_space_len(&after_head);
    if space == 0 {
        return None;
    }
    let raw = &body[HEAD.len() + space..];
    let raw = raw.strip_prefix('`').unwrap_or(raw);
    let token: String = raw
        .chars()
        .take_while(|character| {
            !crate::transcript::jsstr::is_js_space(*character) && *character != '`'
        })
        .collect();
    if token.is_empty() {
        None
    } else {
        Some(token)
    }
}

/// `^fast mode\s+(on|off)\s*[.!…]*$` case-insensitively.
fn fast_mode_set_by_command_output(text: &str) -> Option<String> {
    let body = normalized_suppressed_turn_body(text);
    let lower = ascii_lower(&body);
    let rest = lower.strip_prefix("fast mode")?;
    if leading_space_len(rest) == 0 {
        return None;
    }
    let rest = js_trim_start(rest);
    let state = ["on", "off"]
        .into_iter()
        .find(|state| rest.starts_with(state))?;
    let tail = js_trim(&rest[state.len()..]);
    if !tail
        .chars()
        .all(|character| matches!(character, '.' | '!' | '\u{2026}'))
    {
        return None;
    }
    Some(state.to_uppercase())
}

/// One status row of a harness turn.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StatusRow {
    pub label: String,
    /// `ok`, `error` or `neutral`.
    pub tone: &'static str,
    /// Short trailing fact ("exit code 0") rendered as its own non-wrapping chip.
    pub detail: Option<String>,
}

/// CDXC:SessionChat 2026-09-04 WHY:
/// The harness summary ends in "(exit code N)", and on a wrapped row that parenthetical splits so a
/// lone "0)" lands on the second line. Peeling it off into a chip keeps the number with its words
/// and lets the sentence wrap on its own.
fn split_status_summary(summary: &str) -> (String, Option<String>) {
    let trimmed = js_trim_end(summary);
    let Some(close) = trimmed.strip_suffix(')') else {
        return (summary.to_string(), None);
    };
    let Some(open) = close.rfind('(') else {
        return (summary.to_string(), None);
    };
    let inner = &close[open + 1..];
    let lower = ascii_lower(inner);
    let Some(digits) = lower.strip_prefix("exit code ") else {
        return (summary.to_string(), None);
    };
    let digits = digits.strip_prefix('-').unwrap_or(digits);
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_digit()) {
        return (summary.to_string(), None);
    }
    (js_trim(&close[..open]).to_string(), Some(inner.to_string()))
}

fn js_trim_end(value: &str) -> &str {
    crate::transcript::jsstr::js_trim_end(value)
}

fn task_notification_tone(status: &str) -> &'static str {
    match status {
        "completed" => "ok",
        "failed" => "error",
        // killed/stopped were not failures, they were halted; an empty status is a Monitor event.
        // Neither deserves a red row.
        _ => "neutral",
    }
}

fn tagged_bodies<'a>(text: &'a str, tag: &str) -> Vec<&'a str> {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let lower = ascii_lower(text);
    let mut found = Vec::new();
    let mut cursor = 0;
    while let Some(at) = lower[cursor..].find(&open) {
        let start = cursor + at + open.len();
        let Some(end) = lower[start..].find(&close) else {
            break;
        };
        found.push(&text[start..start + end]);
        cursor = start + end + close.len();
    }
    found
}

/// One status row per `<task-notification>`, or an empty list when none parse.
pub fn parse_task_notifications(text: &str) -> Vec<StatusRow> {
    let mut rows = Vec::new();
    for block in tagged_bodies(text, "task-notification") {
        let status = ascii_lower(js_trim(
            tagged_bodies(block, "status")
                .first()
                .copied()
                .unwrap_or_default(),
        ));
        let summary = js_trim(&collapse_whitespace(
            tagged_bodies(block, "summary")
                .first()
                .copied()
                .unwrap_or_default(),
        ))
        .to_string();
        if summary.is_empty() && status.is_empty() {
            continue;
        }
        // The summary already states what ran and how it ended. Without one, the status is all
        // there is to say.
        let source = if summary.is_empty() {
            format!("Background task {status}")
        } else {
            summary.clone()
        };
        let (label, detail) = split_status_summary(&source);
        rows.push(StatusRow {
            label,
            tone: task_notification_tone(&status),
            detail,
        });
    }
    rows
}

/// How a harness turn is surfaced.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SuppressedTurn {
    /// Never surfaced: the agent's own TUI does not print it either.
    Hidden,
    /// One-line marker that expands to the full text on click.
    Collapsed { label: String },
    /// A polished, non-expandable status row for a completed UI action.
    Status {
        label: String,
        tone: Option<&'static str>,
    },
}

/// The marker label for a harness-injected turn, `Some("")` when the turn is one the terminal never
/// shows either, or `None` when it is a genuine user turn.
fn harness_injected_turn_label(text: &str) -> Option<String> {
    let normalized = ascii_lower(js_trim(text));
    if normalized.is_empty() {
        return None;
    }
    if let Some(tag) = leading_tag_name(&normalized) {
        if let Some(label) = collapsed_tag_label(tag) {
            return Some(label.to_string());
        }
        if is_hidden_tag(tag) {
            return Some(String::new());
        }
    }
    COLLAPSED_PREFIX_LABELS
        .iter()
        .find(|(prefix, _)| normalized.starts_with(prefix))
        .map(|(_, label)| (*label).to_string())
}

fn is_context_compaction_record(message: &ChatMessage, text: &str) -> bool {
    message.role == ChatRole::System
        && message.source == ChatSource::Transcript
        && js_trim(text) == CONTEXT_COMPACTED_LABEL
}

/// Whether the agent's transcript recorded a finished compaction here: Claude's `/compact` output,
/// or the "Context compacted" row gxserver decodes for Codex and Hermes.
pub fn is_compaction_record(message: &ChatMessage) -> bool {
    matches!(
        classify_suppressed_turn(message),
        Some(SuppressedTurn::Status { ref label, .. })
            if label == CONTEXT_COMPACTED_LABEL || label == COMPACTION_COMPLETED_LABEL
    )
}

/// CDXC:SessionChat 2026-10-07 DECISION:
/// Sven: an Empryo model or effort change shows as a status row like Claude's model and effort rows. Empryo prints no command output for one, so gxserver records it as a transcript system row in the words Claude's pill uses ("Set model to gpt-6.1-sol", "Set effort level to high"), placed where the change happened.
/// SEE-ALSO: server/src/session_chat_empryo_notes.rs
fn setting_status_label(message: &ChatMessage, text: &str) -> Option<String> {
    if message.role != ChatRole::System || message.source != ChatSource::Transcript {
        return None;
    }
    if let Some(effort) = effort_set_by_command_output(text) {
        return Some(format!("Set effort level to {}", effort_label(&effort)));
    }
    let text = collapse_whitespace(text);
    if !ascii_lower(&text).starts_with("set model to ") {
        return None;
    }
    // "… with high effort" reads with the effort's display label, as every effort in chat does.
    Some(
        match text
            .rsplit_once(" with ")
            .and_then(|(head, tail)| Some((head, tail.strip_suffix(" effort")?)))
        {
            Some((head, level)) => format!("{head} with {} effort", effort_label(level)),
            None => text,
        },
    )
}

/// A model or effort change the agent's transcript recorded as its own row, which stays in view
/// where it happened instead of folding into the turn's work.
pub fn is_setting_status(message: &ChatMessage) -> bool {
    message.role == ChatRole::System
        && message.source == ChatSource::Transcript
        && setting_status_label(message, js_trim(&joined_text(&message.blocks))).is_some()
}

/// A row after a turn's reply that belongs between turns rather than in the turn's work: a
/// compaction, or a model or effort change.
pub fn is_turn_seam(message: &ChatMessage) -> bool {
    is_compaction_record(message) || is_setting_status(message)
}

/// Which marker, status row, or nothing a turn renders as.
pub fn classify_suppressed_turn(message: &ChatMessage) -> Option<SuppressedTurn> {
    let text = js_trim(&joined_text(&message.blocks)).to_string();
    if message.role == ChatRole::System && message.source == ChatSource::Client {
        if let Some(fast_mode) = fast_mode_set_by_command_output(&text) {
            return Some(SuppressedTurn::Status {
                label: format!("Fast mode {fast_mode}"),
                tone: None,
            });
        }
    }
    if message.role != ChatRole::User && message.role != ChatRole::System {
        return None;
    }
    // A `/btw` pair folded into one row (side_question.rs): a harness row, never a turn of its own.
    if crate::transcript::side_question::is_side_question_message(message) {
        return Some(SuppressedTurn::Collapsed {
            label: crate::transcript::side_question::SIDE_QUESTION_LABEL.to_string(),
        });
    }
    if message.blocks.iter().any(|block| {
        matches!(
            block,
            ChatBlock::ToolCall { .. } | ChatBlock::ToolResult { .. }
        )
    }) {
        return None;
    }
    // A peer Claude session's message is the message-from-another-agent card, a turn of its own
    // like a `ghostex agents send` message, not a harness marker.
    if message.role == ChatRole::User && parse_cross_session_message(&text).is_some() {
        return None;
    }
    // gxserver's own row for an interrupted turn (Codex's `turn_aborted`, Claude's `interruptedMessageId`): the same marker Claude's "[Request interrupted" prompt gets, kept under the prompt instead of folded into "Worked for".
    if message.role == ChatRole::System
        && message.source == ChatSource::Transcript
        && text.to_lowercase() == crate::session::constants::TRANSCRIPT_INTERRUPTED_TEXT
    {
        return Some(SuppressedTurn::Collapsed {
            label: "Interrupted".to_string(),
        });
    }
    if let Some(label) = setting_status_label(message, &text) {
        return Some(SuppressedTurn::Status { label, tone: None });
    }
    if is_context_compaction_record(message, &text) {
        // Same completed-action pill Claude's compaction gets, so the seam reads identically
        // whichever CLI drew it.
        return Some(SuppressedTurn::Status {
            label: CONTEXT_COMPACTED_LABEL.to_string(),
            tone: None,
        });
    }
    let label = harness_injected_turn_label(&text)?;
    if label.is_empty() || suppressed_turn_body(&text).is_empty() {
        // Hidden class, or pure markup with no readable content.
        return Some(SuppressedTurn::Hidden);
    }
    if label == "Local command output" && is_compaction_command_output(&text) {
        return Some(SuppressedTurn::Status {
            label: COMPACTION_COMPLETED_LABEL.to_string(),
            tone: None,
        });
    }
    let command = parse_command_envelope(&text);
    let command_name = command.as_ref().map(|envelope| ascii_lower(&envelope.name));
    if label == "Slash command"
        && matches!(
            command_name.as_deref(),
            Some("/model" | "/effort" | "/fast" | "/compact")
        )
    {
        // The local-command output owns the one user-facing result row.
        return Some(SuppressedTurn::Hidden);
    }
    if label == "Local command output" {
        if let Some(result) = hermes_compress_result(&text) {
            return Some(result);
        }
        if let Some(model) = model_set_by_command_output(&text) {
            let name = model.model.replace('`', "");
            return Some(SuppressedTurn::Status {
                label: match &model.effort {
                    Some(effort) => format!("Set model to {name} with {effort} effort"),
                    None => format!("Set model to {name}"),
                },
                tone: None,
            });
        }
        if let Some(effort) = effort_set_by_command_output(&text) {
            // CDXC:SessionChat 2026-10-01 DECISION: User: show a successful `/effort` or `/fast` as
            // its own completed-action pill, with the effort in the same display capitalization
            // used everywhere else in chat; an `/effort` right after a `/model` folds into the
            // model's pill instead (`fold_model_effort_pairs`), superseding the 2026-09-09 pill
            // beside the model change.
            return Some(SuppressedTurn::Status {
                label: format!("Set effort level to {}", effort_label(&effort)),
                tone: None,
            });
        }
        if let Some(fast_mode) = fast_mode_set_by_command_output(&text) {
            return Some(SuppressedTurn::Status {
                label: format!("Fast mode {fast_mode}"),
                tone: None,
            });
        }
    }
    if label == "Task notification" {
        if let Some(first) = parse_task_notifications(&text).into_iter().next() {
            return Some(SuppressedTurn::Status {
                label: first.label,
                tone: Some(first.tone),
            });
        }
    }
    Some(SuppressedTurn::Collapsed { label })
}

/// A local or slash command's printed output (`<local-command-stdout>`, Codex's `bash-stdout`), which
/// is the command's answer: the agent writes no reply to one.
pub fn is_command_output_turn(message: &ChatMessage) -> bool {
    message.role == ChatRole::User
        && !is_hidden_message(message)
        && harness_injected_turn_label(js_trim(&joined_text(&message.blocks))).as_deref()
            == Some("Local command output")
}

/// True only for turns that must not reach the list at all.
pub fn is_hidden_message(message: &ChatMessage) -> bool {
    matches!(
        classify_suppressed_turn(message),
        Some(SuppressedTurn::Hidden)
    )
}

/// The collapsed-marker label, or `None` when the turn renders normally.
pub fn suppressed_turn_label(message: &ChatMessage) -> Option<String> {
    match classify_suppressed_turn(message) {
        Some(SuppressedTurn::Collapsed { label }) | Some(SuppressedTurn::Status { label, .. }) => {
            Some(label)
        }
        _ => None,
    }
}

/// CDXC:SessionChat 2026-09-10 DECISION:
/// User: a slash command the reader sent starts its own turn in the chat summary. Claude answers
/// each intercepted command with "No response requested.", and while a command row only continued
/// the turn before it, that reply became the turn's final message and folded the real answer away
/// under "Worked for".
pub fn is_command_turn(message: &ChatMessage) -> bool {
    message.role == ChatRole::User
        && suppressed_turn_label(message).as_deref() == Some("Slash command")
}

/// Drop only the never-surfaced turns; collapsed markers stay in the list.
pub fn drop_hidden_messages(messages: &[ChatMessage]) -> Vec<ChatMessage> {
    messages
        .iter()
        .filter(|message| !is_hidden_message(message))
        .cloned()
        .collect()
}

fn fits_inline_suppressed_turn(body: &str) -> bool {
    !body.is_empty()
        && crate::transcript::jsstr::utf16_len(body) <= INLINE_BODY_MAX_CHARS
        && body.split('\n').count() <= INLINE_BODY_MAX_LINES
}

fn status_row_value(row: &StatusRow) -> Value {
    let mut entry = Map::new();
    entry.insert("label".to_string(), row.label.clone().into());
    entry.insert("tone".to_string(), row.tone.into());
    if let Some(detail) = &row.detail {
        entry.insert("detail".to_string(), detail.clone().into());
    }
    Value::Object(entry)
}

/// Human-readable label and expandable text for a suppressed harness turn, or `Value::Null`.
///
/// `kind` is `collapsed`, `inline` (a short collapsed turn shown as prose instead of a chevron) or
/// `status`.
pub fn suppressed_turn_presentation(message: &ChatMessage) -> Value {
    let suppressed = classify_suppressed_turn(message);
    let (kind, label, tone) = match &suppressed {
        Some(SuppressedTurn::Collapsed { label }) => ("collapsed", label.clone(), None),
        Some(SuppressedTurn::Status { label, tone }) => ("status", label.clone(), *tone),
        _ => return Value::Null,
    };

    let raw_text = js_trim(&joined_text(&message.blocks)).to_string();

    if kind == "status" {
        let statuses = parse_task_notifications(&raw_text);
        if !statuses.is_empty() {
            let mut out = Map::new();
            out.insert("kind".to_string(), "status".into());
            out.insert("label".to_string(), label.clone().into());
            out.insert("text".to_string(), raw_text.clone().into());
            if let Some(tone) = tone {
                out.insert("tone".to_string(), tone.into());
            }
            out.insert(
                "statuses".to_string(),
                Value::Array(statuses.iter().map(status_row_value).collect()),
            );
            return Value::Object(out);
        }
    }

    let command = parse_command_envelope(&raw_text);
    let model = model_set_by_command_output(&raw_text);
    let is_local_command = label == "Local command" || label == "Local command output";
    let body = if is_local_command {
        suppressed_turn_body(&raw_text)
    } else {
        raw_text.clone()
    };
    let mut text = strip_ansi(&body);
    if command
        .as_ref()
        .map(|envelope| ascii_lower(&envelope.name))
        .as_deref()
        == Some("/model")
    {
        text = command.expect("a matched name implies an envelope").name;
    } else if let Some(model) = &model {
        text = normalized_suppressed_turn_body(&raw_text);
        if let Some(note) = &model.note {
            // The pin warning is a second fact about the same action, not chrome to drop: it gets
            // its own neutral row under the model result.
            let statuses = vec![
                status_row_value(&StatusRow {
                    label: label.clone(),
                    tone: if kind == "status" {
                        tone.unwrap_or("ok")
                    } else {
                        "ok"
                    },
                    detail: None,
                }),
                json!({ "label": note, "tone": "neutral" }),
            ];
            return json!({
                "kind": "status",
                "label": label,
                "text": text,
                "statuses": statuses,
            });
        }
    }

    // Short harness turns read as prose; the body without its markup IS the sentence, so the inline
    // row shows that rather than the raw envelope.
    if kind == "collapsed" {
        let body = strip_ansi(&suppressed_turn_body(&raw_text));
        if fits_inline_suppressed_turn(&body) {
            return json!({ "kind": "inline", "label": label, "text": body });
        }
    }

    let mut out = Map::new();
    out.insert("kind".to_string(), kind.into());
    out.insert("label".to_string(), label.into());
    out.insert("text".to_string(), text.into());
    if kind == "status" {
        if let Some(tone) = tone {
            out.insert("tone".to_string(), tone.into());
        }
    }
    Value::Object(out)
}
