//! Settings keys the Settings window shows without a search row of their own (or under a UI id),
//! so `ghostex settings` and the Help files still have a key to name. The Settings window stays the
//! source of the copy; these rows only place the key on the right page.

use crate::data::{DEFAULT_EDITOR_COMMAND_OPTIONS, SESSION_TITLE_GENERATION_AGENT_OPTIONS};
use crate::json::{opt, Opt};

/// A Settings page as the Help files name it: its id and title.
pub(crate) type Tab = (&'static str, &'static str);

pub(crate) const GENERAL: Tab = ("settings", "General");
/// The Theme page renders the `appearance` group's sections (Theme, App Icon) on its own tab.
pub(crate) const THEME: Tab = ("theme", "Theme");
const EXTENSIONS: Tab = ("extensions", "Extensions");
const AGENTS: Tab = ("agents", "Agents");
const PROJECTS: Tab = ("projects", "Projects");
const OPEN_TARGETS: Tab = ("openTargets", "Open In");
const HOTKEYS: Tab = ("hotkeys", "Hotkeys");
const INTEGRATIONS: Tab = ("integrations", "Integrations");
const ABOUT: Tab = ("about", "About");
const ACCOUNTS: Tab = ("accounts", "Accounts");
const REMOTE: Tab = ("remote", "Remote");

pub(crate) struct Supplemental {
    pub(crate) key: &'static str,
    pub(crate) tab: Tab,
    pub(crate) group: Option<&'static str>,
    pub(crate) section: &'static str,
    pub(crate) section_title: &'static str,
    pub(crate) title: &'static str,
    pub(crate) subtitle: &'static str,
    pub(crate) options: &'static [Opt],
    /// Never agent-writable: values the app derives or that belong to the user alone.
    pub(crate) user_only: bool,
}

pub(crate) const SUPPLEMENTAL_ROWS: &[Supplemental] = &[
    Supplemental {
        key: "agentAcceptAllEnabled",
        tab: AGENTS,
        group: None,
        section: "config",
        section_title: "Config",
        title: "Agent approvals: accept all",
        subtitle: "Start supported agents with approvals turned off (full access) by default. Off keeps each agent CLI default approval mode. Projects can override it.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "defaultPromptAgentId",
        tab: AGENTS,
        group: None,
        section: "config",
        section_title: "Config",
        title: "Default Prompt Agent",
        subtitle: "Agent id used when Ghostex sends a prompt on your behalf (for example PR review). Use an id from the configured agents.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "sessionTitleGenerationAgent",
        tab: AGENTS,
        group: None,
        section: "config",
        section_title: "Config",
        title: "Title Generation Agent",
        subtitle: "Headless agent Ghostex uses for first-prompt session title generation.",
        options: SESSION_TITLE_GENERATION_AGENT_OPTIONS,
        user_only: false,
    },
    Supplemental {
        key: "customSessionTitleGenerationCommand",
        tab: AGENTS,
        group: None,
        section: "config",
        section_title: "Config",
        title: "Custom Title Command",
        subtitle: "Custom command run with the title prompt on stdin when Title Generation Agent is custom. It should print only the title.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "ghostexCaptureEnabled",
        tab: INTEGRATIONS,
        group: None,
        section: "ghostexCapture",
        section_title: "Floating Capture",
        title: "Show the floating button",
        subtitle: "Show the Floating Capture button over every app: agent counts, screenshots of an area, an app or the whole screen, and quick prompts without switching to Ghostex.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "ghostexCaptureSwitchToSession",
        tab: INTEGRATIONS,
        group: None,
        section: "ghostexCapture",
        section_title: "Floating Capture",
        title: "Switch to the session after sending",
        subtitle: "After a prompt is sent from Floating Capture, the Ghostex window shows the session it went to, without coming in front of the app you are in.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "showAdvancedSettings",
        tab: GENERAL,
        group: None,
        section: "settingsModal",
        section_title: "Settings window",
        title: "Show Advanced settings",
        subtitle: "Show the rows marked Advanced in Settings.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "codeViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Code view",
        subtitle: "Stop offering the Code view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "browserViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Browser view",
        subtitle: "Stop offering the Browser view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "kanbanViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Kanban view",
        subtitle: "Stop offering the Kanban view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "automateViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Automate view",
        subtitle: "Stop offering the Automate view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "docsViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Files view",
        subtitle: "Stop offering the Files view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "linearViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Linear view",
        subtitle: "Hide the Linear view from the view picker and tab menus.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "jiraViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Jira view",
        subtitle: "Hide the Jira view from the view picker and tab menus.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "githubViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide GitHub view",
        subtitle: "Hide the automatic repository view from the view picker and tab menus.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "sentryViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Sentry view",
        subtitle: "Enable Sentry in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "figmaViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Figma view",
        subtitle: "Enable Figma in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "vercelViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Vercel view",
        subtitle: "Enable Vercel in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "supabaseViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Supabase view",
        subtitle: "Enable Supabase in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "githubActionsViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide GitHub Actions view",
        subtitle: "Enable GitHub Actions in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "posthogViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide PostHog view",
        subtitle: "Enable PostHog in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "customWebsiteViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Custom Website view",
        subtitle: "Enable Custom Website in Settings > Extensions, then choose its home URL when opening the view. Disabled by default.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "storybookViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Storybook view",
        subtitle: "Hide the built-in component workshop. When enabled, it appears only in projects with Storybook.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "terminalViewTabHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Terminal view",
        subtitle: "Stop offering the Terminal view, so it is missing from the view panel tab strip, its + menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "botsHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Hide Bots",
        subtitle: "Stop offering Bots, the sidebar mode with one row per Hermes profile. Hidden by default; offered only where the Hermes CLI is installed.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "botAutomationsHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Hide Bot automations",
        subtitle: "Stop offering Bot automations, the Automations row in the Bots sidebar that opens a feed of every Hermes cron run. Hidden by default; needs Bots.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "tipsAndTricksTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Tips button",
        subtitle: "Stop offering the Tips & Tricks page, so it is missing from the header ⋯ menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "notificationsTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Notifications bell",
        subtitle: "Hide the Notifications bell from the sidebar's top row.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "helpTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Help button",
        subtitle: "Stop offering the Ask Ghostex page, so it is missing from the header ⋯ menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "resourcesTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Resources button",
        subtitle: "Stop offering the Resources page, so it is missing from the header ⋯ menu and the view picker.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "devServersTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Dev Servers button",
        subtitle: "Hide Dev servers from the header ⋯ menu.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "extensionsTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Extensions button",
        subtitle: "Hide Extensions from the header ⋯ menu.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "gitActionsTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "viewOrder",
        section_title: "Views",
        title: "Hide Git button",
        subtitle: "Hide the Commit button from the work area header.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "actionsHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Turn off Actions",
        subtitle: "Turn off Actions everywhere: the Start button, the Actions page in Settings, Actions pinned to project rows, the Start Action hotkeys and the Quick Access rows. Off by default; your saved actions are kept.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "openInTitlebarButtonHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Turn off Open In",
        subtitle: "Turn off Open In everywhere: the Open button, the Open In page in Settings and the Open In menus. Your apps and custom commands are kept.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "sidebarSpacesEnabled",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Spaces",
        subtitle: "Turn on Spaces: a row of Space icons at the top of the sidebar, Space menus, and the Space settings. Off by default; your saved Spaces are kept while it is off.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "cloudBoxesHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Turn off Cloud Boxes",
        subtitle: "Turn off Cloud Boxes everywhere: the Cloud Boxes page in Settings, the Run on choice of a new thread, Run in a Box in the Select Agent menu and the agentbox commands. Off by default; your boxes and box settings are kept.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "workspacesHidden",
        tab: EXTENSIONS,
        group: None,
        section: "official",
        section_title: "Built-in",
        title: "Turn off Workspaces",
        subtitle: "Turn off Workspaces and work mode everywhere: the workspace button, the Workspaces page in Settings, Work mode on projects, the Work view, Linear and GitHub links on sessions and the workspace commands. Off by default; your workspaces, links, keys and team connections are kept.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "defaultEditorCommand",
        tab: OPEN_TARGETS,
        group: None,
        section: "defaultEditor",
        section_title: "Default editor",
        title: "Default editor",
        subtitle: "Editor command used by Open In and `ghostex edit` when no other target is chosen.",
        options: DEFAULT_EDITOR_COMMAND_OPTIONS,
        user_only: false,
    },
    Supplemental {
        key: "customDefaultEditorCommand",
        tab: OPEN_TARGETS,
        group: None,
        section: "defaultEditor",
        section_title: "Default editor",
        title: "Custom editor command",
        subtitle: "Command used when Default editor is set to other.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "manageAdditionalDocsFolders",
        tab: PROJECTS,
        group: None,
        section: "docs",
        section_title: "Files",
        title: "Additional docs folders",
        subtitle: "Extra folders (one per line) the Files view lists in every project.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "globalBeadsDisplayKey",
        tab: PROJECTS,
        group: None,
        section: "globalDefaults",
        section_title: "Global Defaults",
        title: "Global ticket key",
        subtitle: "Default ticket key prefix shown on Kanban cards when a project has none.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "analyticsEnabled",
        tab: ABOUT,
        group: None,
        section: "privacy",
        section_title: "Privacy",
        title: "Anonymous analytics",
        subtitle: "Send anonymous usage analytics. Ask the user before changing it.",
        options: &[],
        user_only: true,
    },
    Supplemental {
        key: "hideAccountEmails",
        tab: ACCOUNTS,
        group: None,
        section: "accounts",
        section_title: "Accounts",
        title: "Hide account emails",
        subtitle: "Hide account email addresses in the Accounts page and account switchers.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "expandCollapsedProjectsOnJump",
        tab: HOTKEYS,
        group: None,
        section: "projects",
        section_title: "Projects",
        title: "Expand collapsed projects on jump",
        subtitle: "Expand a collapsed project when a project-jump hotkey lands on it.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "showLessForExpandedProjectJumps",
        tab: HOTKEYS,
        group: None,
        section: "projects",
        section_title: "Projects",
        title: "Compact list after project jumps",
        subtitle: "Switch the session list of a project expanded by a jump to Compact.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "sidebarSessionCycleSkipsSleeping",
        tab: HOTKEYS,
        group: None,
        section: "navigation",
        section_title: "Navigation",
        title: "Skip sleeping sessions",
        subtitle: "Next Session and Previous Session jump over sleeping sessions in the sidebar.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "windowsTerminalBackend",
        tab: GENERAL,
        group: Some("terminal"),
        section: "terminal",
        section_title: "Terminal",
        title: "Windows Environment",
        subtitle: "Windows only. PowerShell (default) runs native Windows projects and agents. WSL runs Linux projects. Changing environments prompts you to restart Ghostex.",
        options: &[opt("PowerShell (Native)", "powershell"), opt("WSL (Linux)", "wsl")],
        user_only: false,
    },
    Supplemental {
        key: "windowsWslDistribution",
        tab: GENERAL,
        group: Some("terminal"),
        section: "terminal",
        section_title: "Terminal",
        title: "WSL distribution",
        subtitle: "Windows only. Exact distro name from `wsl.exe --list --verbose`; blank uses automatic WSL2 discovery.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "portlessEnabled",
        tab: PROJECTS,
        group: None,
        section: "portless",
        section_title: "Portless",
        title: "Portless",
        subtitle: "Route project dev servers through named local addresses instead of raw ports.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "portlessProtocol",
        tab: PROJECTS,
        group: None,
        section: "portless",
        section_title: "Portless",
        title: "Portless protocol",
        subtitle: "Protocol Portless addresses use.",
        options: &[opt("HTTPS", "https"), opt("HTTP", "http")],
        user_only: false,
    },
    Supplemental {
        key: "workspacePaneGap",
        tab: THEME,
        group: Some("appearance"),
        section: "theming",
        section_title: "Theme",
        title: "Pane gap",
        subtitle: "Gap in pixels between split panes in the Agents view.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "customSidebarTitlebarForegroundColor",
        tab: THEME,
        group: Some("appearance"),
        section: "theming",
        section_title: "Theme",
        title: "Sidebar foreground color (derived)",
        subtitle: "Derived from Background Contrast and Background Tint; change those instead.",
        options: &[],
        user_only: true,
    },
    Supplemental {
        key: "customSidebarTitlebarBackgroundColor",
        tab: THEME,
        group: Some("appearance"),
        section: "theming",
        section_title: "Theme",
        title: "Sidebar background color (derived)",
        subtitle: "Derived from Background Contrast and Background Tint; change those instead.",
        options: &[],
        user_only: true,
    },
    Supplemental {
        key: "petOverlayEnabled",
        tab: GENERAL,
        group: Some("statusIndicators"),
        section: "statusIndicators",
        section_title: "Status Indicators",
        title: "Pet overlay",
        subtitle: "Show the draggable animated pet in the sidebar (also Wake Pet / Sleep Pet in Quick Access).",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "selectedPetId",
        tab: GENERAL,
        group: Some("statusIndicators"),
        section: "statusIndicators",
        section_title: "Status Indicators",
        title: "Pet",
        subtitle: "Which pet sprite the overlay shows.",
        options: &[],
        user_only: false,
    },
    Supplemental {
        key: "remoteTailscaleEnabled",
        tab: REMOTE,
        group: None,
        section: "tailscale",
        section_title: "Tailscale",
        title: "Tailscale on or off",
        subtitle: "Offer the Tailscale path in Remote setup.",
        options: &[],
        user_only: false,
    },
];
